### PR TITLE
Update active record-session_store dependency

### PR DESCRIPTION
**Pull request by benjaminwols**
Activerecord-session_store version 0.1.1 uses Thread.exclusive which is deprecated in Ruby 2.3.0
They have released a new version 1.0.0.pre which fixes this issue, so the dependency needs to be loosened.

### CODE REVIEW

**Comment by djcp** [comment]
Thanks! My only concern is that this'll install any version of activerecord-session_store >= 0.1.1, which isn't deterministic enough as new versions of this dependent gem is released. Can you try optimistically locking to `~> 1.0.0` and see if we get the pre release as well?

**Comment by benjaminwols** [comment]
I tried locking to `~> 1.0.0` but it doesn't work with the pre release. I now locked to the pre release `~> 1.0.0.pre`

**Comment by djcp** [comment]
Thanks! So I can merge this into master but I think it'd be weird to cut a release off an RC dependency. Thoughts? I'll ping @sikachu (the https://github.com/rails/activerecord-session_store maintainer) to see if he has thoughts on when 1.0.0 will get a release proper.  If it's coming soon, then maybe we can wait until then (and  you can continue to use a github branch in your Gemfile). If it's not coming soon, then we can revisit then.

**Comment by djcp** [comment]
Asked and answered: https://github.com/rails/activerecord-session_store/issues/78

**Comment by djcp** [comment]
Does it sound OK with you to wait until the official rails 5 release, which should mean the official 1.0.0 release date of activerecord-session_store?

**Comment by benjaminwols** [comment]
Sure that is no problem for me. I will keep using my fork with the 1.0.0.pre dependency for now. Thanks for thinking along.

**Comment by benjaminwols** [comment]
I messed up this PR with different commits. 
I will make a new PR when rails 5 has been released and activerecord-session_store has release v1.0.0

**Pull request closed without merging**
